name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
            sudo apt-get update
            sudo apt-get install wget make musl-tools perl automake libtool pkgconf
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Tor
        run: make -j
      - name: Strip Tor
        run: strip ./install/bin/tor
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Testing Build"
          files: |
            ./LICENSE
            ./install/bin/tor
