name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
            sudo apt-get update
            sudo apt-get install wget make perl automake libtool pkgconf
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Tor
        run: |
            wget x86_64-linux-musl-native.tgz
            tar xvf x86_64-linux-musl-native.tgz
            PATH=$PWD/x86_64-linux-musl-native/bin:$PATH
            make -j
      - name: Strip Tor
        run: strip ./install/bin/tor
      - name: Compress LICENSES
        run: |
            mv ./LICENSE ./LICENSES/
            tar cvf LICENSES.tar.gz LICENSES
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Testing Build"
          files: |
            ./LICENSES.tar.gz
            ./install/bin/tor
